DATA_VALIDATION_DIR_NAME: str = "data_validation_artifact"
DATA_VALIDATION_VALID_DIR: str = "valid data"
DATA_VALIDATION_INVALID_DIR: str = "invalid data"
DATA_VALIDATION_REPORT_DIR: str = "report"
DATA_VALIDATION_MISSING_COLUMNS_REPORT_HTML_FILE: str = "missing_columns_report.html"
DATA_VALIDATION_DRIFT_REPORT_DIR: str = "drift report"
DATA_VALIDATION_DRIFT_REPORT_YAML_FILE: str = "drift_report.yaml"
DATA_VALIDATION_DRIFT_REPORT_HTML_FILE: str = "drift_report.html"
